services:
  proxy:
    image: ubuntu/squid:latest
    container_name: ai-proxy
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro

  ai-browser:
    build: .
    container_name: ai-browser
    depends_on:
      - proxy
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ai_browser_artifacts:/artifacts
      - ai_browser_user_data:/home/pwuser/browser-data
      - ./seccomp_profile.json:/seccomp_profile.json:ro
    environment:
      HTTP_PROXY: http://proxy:3128
      HTTPS_PROXY: http://proxy:3128
      PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
    shm_size: "1gb" # デフォルト値64mbだと小さすぎるので設定
    init: true # pid:1 のinit的なことやってくれるらしい入れておくとゾンビの回収してくれるので安定するらしい

volumes:
  ai_browser_artifacts:
  ai_browser_user_data:
